# Generated by Django 4.0.5 on 2022-07-12 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='Код комнаты')),
                ('started', models.BooleanField(default=False, verbose_name='Игра запущена')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('session', models.CharField(blank=True, max_length=150, unique=True, verbose_name='Сессия')),
                ('correct_answer', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.rooms')),
            ],
        ),
    ]
