# Generated by Django 4.0.5 on 2022-07-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='starting',
            field=models.BooleanField(default=False, verbose_name='Игра запуcкается'),
        ),
    ]
